/* @layer renderer-components @kind constants */
const TEXT_ELEMENT_SPECS = [
  { name: 'Paragraph', short: 'P', tag: 'p' },
  { name: 'Span', short: 'Span', tag: 'span' },
  { name: 'Strong', short: 'Strong', tag: 'strong' },
  { name: 'Emphasis', short: 'Em', tag: 'em' },
  { name: 'Bold', short: 'B', tag: 'b' },
  { name: 'Italic', short: 'I', tag: 'i' },
  { name: 'Underline', short: 'U', tag: 'u' },
  { name: 'Strikethrough', short: 'S', tag: 's' },
  { name: 'Deleted', short: 'Del', tag: 'del' },
  { name: 'Inserted', short: 'Ins', tag: 'ins' },
  { name: 'Highlight', short: 'Mark', tag: 'mark' },
  { name: 'Small', short: 'Small', tag: 'small' },
  { name: 'Subscript', short: 'Sub', tag: 'sub' },
  { name: 'Superscript', short: 'Sup', tag: 'sup' },
  { name: 'Code', short: 'Code', tag: 'code' },
  { name: 'Keyboard', short: 'Kbd', tag: 'kbd' },
  { name: 'Sample', short: 'Samp', tag: 'samp' },
  { name: 'Variable', short: 'Var', tag: 'var' },
  { name: 'Abbreviation', short: 'Abbr', tag: 'abbr' },
  { name: 'Citation', short: 'Cite', tag: 'cite' },
  { name: 'Quote', short: 'Q', tag: 'q' },
  { name: 'BlockQuote', short: 'Blockquote', tag: 'blockquote' },
  { name: 'Definition', short: 'Dfn', tag: 'dfn' },
  { name: 'Time', short: 'Time', tag: 'time' },
  { name: 'Data', short: 'Data', tag: 'data' },
  { name: 'Address', short: 'Address', tag: 'address' },
  { name: 'Preformatted', short: 'Pre', tag: 'pre' },
  { name: 'BidiIsolate', short: 'Bdi', tag: 'bdi' },
  { name: 'BidiOverride', short: 'Bdo', tag: 'bdo' },
  { name: 'Ruby', short: 'Ruby', tag: 'ruby' },
  { name: 'RubyText', short: 'Rt', tag: 'rt' },
  { name: 'RubyParenthesis', short: 'Rp', tag: 'rp' },
] as const;

export { TEXT_ELEMENT_SPECS };
