/* @layer renderer-components @kind data */
const DEFAULT_LIST_WIDTH = 320;
const DEFAULT_MIN_LIST_WIDTH = 240;
const DEFAULT_MAX_LIST_WIDTH = 480;
const WIDTH_STEP = 16;
const WIDTH_STEP_LARGE = 64;
const COLLAPSED_KEY_SUFFIX = ':collapsed';

export { COLLAPSED_KEY_SUFFIX, DEFAULT_LIST_WIDTH, DEFAULT_MAX_LIST_WIDTH, DEFAULT_MIN_LIST_WIDTH, WIDTH_STEP, WIDTH_STEP_LARGE };
