/* @layer renderer-components @kind data */
const COMMON_STRINGS = {
  loading: 'Loading',
  cancel: 'Cancel',
  close: 'Close',
  confirm: 'Confirm',
  create: 'Create',
  delete: 'Delete',
  done: 'Done',
  open: 'Open',
  options: 'Options',
  remove: 'Remove',
  reset: 'Reset',
  save: 'Save',
  search: 'Search',
  searchPlaceholder: 'Search...',
  filterPlaceholder: 'Filter...',
  noMatches: 'No matches',
  nothingToShow: 'Nothing to show.',
  copied: 'Copied',
  copyNamed: (name: string) => (name ? `Copy ${name}` : 'Copy'),
  yes: 'Yes',
  no: 'No',
  mute: 'Mute',
  unmute: 'Unmute',
  volume: 'Volume',
  volumeHint: 'How loud the sound plays',
  muteHint: 'Silences the sound and keeps the level',
  unmuteHint: 'Brings the sound back at the level it had',
  play: 'Play',
  pause: 'Pause',
  popIn: 'Pop in',
  popOut: 'Pop out',
  hintIdle: 'Point at an option to see what it does',
  selectedCount: (count: number) => `${count} selected`,
  removeNamed: (name: string) => `Remove ${name}`,
  reportIssue: 'Report an issue',
  retry: 'Retry',
  retryNow: 'Retry now',
  nextTryIn: (wait: string) => `Next try in ${wait}`,
  tryOfIn: (attempt: number, attempts: number, wait: string) => `Try ${attempt} of ${attempts} in ${wait}`,
  tryOf: (attempt: number, attempts: number) => `Try ${attempt} of ${attempts}`,
  waitSeconds: (seconds: number) => `${seconds} s`,
  waitMinutes: (minutes: number, seconds: number) => (seconds > 0 ? `${minutes} min ${seconds} s` : `${minutes} min`),
  send: 'Send',
  command: 'Command',
  history: 'history',
  clear: 'clear',
  complete: 'complete',
  commands: 'Commands',
  repeated: (count: number) => `Shown ${count} times`,
  repeatedShort: (count: number) => `×${count}`,
};

export { COMMON_STRINGS };
