/* @layer renderer-components @kind data */
const COMMON_STRINGS = {
  loading: 'Loading',
  cancel: 'Cancel',
  close: 'Close',
  confirm: 'Confirm',
  create: 'Create',
  delete: 'Delete',
  done: 'Done',
  options: 'Options',
  remove: 'Remove',
  reset: 'Reset',
  save: 'Save',
  search: 'Search',
  searchPlaceholder: 'Search...',
  filterPlaceholder: 'Filter...',
  noMatches: 'No matches',
  nothingToShow: 'Nothing to show.',
  copied: 'Copied',
  copyNamed: (name: string) => (name ? `Copy ${name}` : 'Copy'),
  yes: 'Yes',
  no: 'No',
  mute: 'Mute',
  unmute: 'Unmute',
  volume: 'Volume',
  volumeHint: 'How loud the sound plays',
  muteHint: 'Silences the sound and keeps the level',
  unmuteHint: 'Brings the sound back at the level it had',
  play: 'Play',
  pause: 'Pause',
  popIn: 'Pop in',
  popOut: 'Pop out',
  hintIdle: 'Point at an option to see what it does',
  selectedCount: (count: number) => `${count} selected`,
  removeNamed: (name: string) => `Remove ${name}`,
  reportIssue: 'Report an issue',
};

export { COMMON_STRINGS };
