/* @layer renderer-components @kind data */
const OPTION_STRINGS = {
  jsonObject: (keys: number) => `Valid JSON object, ${keys} ${keys === 1 ? 'key' : 'keys'}`,
  jsonArray: (items: number) => `Valid JSON array, ${items} ${items === 1 ? 'item' : 'items'}`,
  jsonValue: 'Valid JSON value',
  jsonAt: (problem: string, line: number, column: number) => `${problem} on line ${line}, column ${column}.`,
  jsonEmpty: 'Write a JSON value, such as {}',
  jsonValueMissing: 'Expected a value',
  jsonUnclosed: 'The text has no closing quote',
  jsonEscape: 'Unknown escape after a backslash',
  jsonControl: 'A tab or control character inside a text',
  jsonNumber: 'Not a valid number',
  jsonKey: 'Expected a key in double quotes',
  jsonColon: "Expected ':' after the key",
  jsonObjectNext: "Expected ',' or '}' after the value",
  jsonArrayNext: "Expected ',' or ']' after the value",
  jsonTrailingComma: 'Remove the comma before the end',
  jsonExtra: 'Unexpected text after the end',
  jsonWantObject: 'Write an object in braces { }',
  jsonWantArray: 'Write a list in brackets [ ]',
  format: 'Format',
  custom: 'Custom',
  namedValue: (label: string, value: number) => `${label} (${value})`,
  range: (min: number, max: number) => `${min} to ${max}`,
  customValue: 'Custom value',
  searchItems: (count: number) => `Search ${count} items`,
  chosen: 'Chosen',
  noMatch: 'Nothing matches.',
  add: 'Add',
  addKey: (count: number) => `Add an item: type to search ${count} items`,
  addFree: 'Add a name',
  keyName: 'Name',
  valueOf: (key: string) => `Value of ${key}`,
  removeKey: (key: string) => `Remove ${key}`,
  listedTwice: (key: string) => `${key} is listed twice.`,
  emptyKey: 'Every row needs a name.',
  unknownKey: (key: string) => `${key} is not on the list.`,
  noEntries: 'Nothing added yet.',
  changed: 'changed',
  advanced: 'advanced',
  reset: (label: string) => `Reset ${label}`,
  groupChanged: (label: string, changed: number) => (changed ? `${label} · ${changed} changed` : label),
  showAdvanced: (count?: number) => (count === undefined ? 'Show advanced' : `Show advanced (${count})`),
  searchOptions: 'Search options',
};

export { OPTION_STRINGS };
