/* @layer renderer-components @kind data */
const PANEL_STRINGS = {
  copyAll: 'Copy all',
  logNoun: (total: number) => (total === 1 ? 'entry' : 'entries'),
  logCount: (shown: number, total: number, noun: string) => (shown === total ? `${total} ${noun}` : `${shown} of ${total} ${noun}`),
  logEmpty: 'No entries.',
  loadOlder: (count: number) => `Load ${count} older`,
  olderHidden: (count: number) => `${count} earlier rows hidden`,
  newest: 'Newest',
  logKind: 'Type',
  logTag: 'Tag',
  logMessage: 'Message',
  logNoMatch: 'No lines match the search and filters.',
  filterLog: 'Filter the log',
  sectionFailed: 'This section could not be shown',
  settingsEmpty: 'Nothing to set here right now.',
  resetSection: (changed: number) => `Reset section to defaults (${changed} changed)`,
  sectionAtDefaults: 'Section is already at its defaults',
  resetToDefaults: 'Reset to defaults',
  keepSettings: 'Keep current settings',
  disabled: 'Disabled',
  openSettings: 'Open Settings',
  overview: 'Overview',
  stickPosition: 'Stick position',
  calibrated: 'cal',
  keyboard: 'Keyboard',
  taskProgress: 'Progress',
  taskRunning: 'Running',
  taskDone: 'Done',
  taskFailed: 'Failed',
  taskCancelled: 'Cancelled',
  showLog: (count: number) => `Show log (${count})`,
  hideLog: 'Hide log',
  hideJob: 'Hide',
};

export { PANEL_STRINGS };
