/* @layer renderer-components @kind data */
const RECORD_STRINGS = {
  noFieldsToShow: 'This record has no fields to show.',
  noFieldsToFill: 'This record has no fields to fill in.',
  createFailed: 'Create failed',
  saveFailed: 'Save failed',
  revert: 'Revert',
  deleteGuardTitle: 'Delete this record?',
  deleteGuardConfirm: 'Delete anyway',
  deleteGuardMessage: (subject: string) =>
    `${subject} is still referenced elsewhere. Deleting it will leave those references dangling.`,
  namePlaceholder: 'Name',
  otherGroup: 'Other',
  nestedNoFields: 'No fields described. Shown as recorded.',
  nestedTooDeep: 'Nested too deep to lay out. Shown as recorded.',
  branchAbsent: 'No value set. Shown as recorded.',
  branchNotObject: 'Not a branch shape. Shown as recorded.',
  branchUnmatched: 'Unrecognised branch. Shown as recorded.',
  alsoHolds: (keys: readonly string[]) => `Also holds, unedited: ${keys.join(', ')}`,
  optional: 'optional',
  add: '+ Add',
  addValue: '+ Add value',
  addGroup: '+ Add group',
  itemPosition: (position: number) => `#${position}`,
  referencedBy: 'Referenced by',
  notReferenced: 'Not referenced anywhere.',
  via: (field: string) => `via ${field}`,
  tagPlaceholder: 'Search or add a tag...',
  chooseShape: 'Choose a shape for this item.',
  shapePlaceholder: 'Shape...',
  diffLive: (source: string, value: string) => `live (${source}): ${value}`,
  itemsNone: 'none',
  itemsOne: '1 item',
  itemsMany: (count: number) => `${count} items`,
  countPlaceholder: 'count',
  notInCollection: 'not in this collection',
  moveUp: 'Move up',
  moveDown: 'Move down',
  rangeFrom: 'from',
  rangeFromLabel: 'From',
  rangeTo: 'to',
  rangeToLabel: 'To',
  objectNoFields: 'No fields',
  otherValue: '+ Other',
  otherValueTitle: (label: string) => `${label}: use a value that is not listed`,
  otherValuePlaceholder: 'a value not listed',
  otherValueLabel: (label: string) => `${label}: a value that is not listed`,
  setValue: 'Set',
  editViaDetail: 'Edit via detail',
};

export { RECORD_STRINGS };
