/* @layer renderer-components @kind data */
const WIDGET_STRINGS = {
  titlebarHint: 'Drag to move. Hold Alt to peek at the main view. While dragging: Shift swaps, Ctrl overlays, Esc cancels, past the window edge pops out.',
  outHint: 'Drag to move the window. Drop it over the app to put it back. Near an edge of the app or another widget, it snaps.',
  pinTitleOff: 'Pin: off. Click for always on top.',
  pinTitleTop: 'Pin: always on top. Click to follow the app.',
  pinTitleWithApp: 'Pin: with the app. Click to unpin.',
  optionsFor: (title: string) => `${title} options`,
  placementSection: 'Placement',
  shortcutsSection: 'Shortcuts',
  resetWidget: 'Reset this widget',
  dockLeft: 'Dock left',
  dockRight: 'Dock right',
  dockTop: 'Dock top',
  dockBottom: 'Dock bottom',
  float: 'Float',
  popInTitle: 'Back into the app, where it was docked before',
  makeRoom: 'Make room',
  makeRoomHint: 'The main view shrinks to fit this widget',
  opacity: 'Opacity',
  show: 'Show',
  showAlways: 'Always',
  contextLabel: 'In context',
  windowSection: 'Window',
  pin: 'Pin',
  pinHint: 'With app: on top exactly when the app is',
  pinOff: 'Off',
  pinOffTitle: 'Behaves like any window',
  pinOnTop: 'On top',
  pinOnTopTitle: 'Always over every other window',
  pinWithApp: 'With app',
  pinWithAppTitle: 'On top exactly when the app is, and comes forward with it',
  snapToEdges: 'Snap to edges',
  snapHint: "The app's and other widgets' windows",
  shortcutDragTitle: 'Drag title',
  shortcutDragTitleDoes: 'Move to a dock edge, a pane, a tab or over the main view',
  shortcutPeekDoes: 'Peek: widgets fold away while held',
  shortcutPlusDrop: '+ drop',
  shortcutSwapDoes: 'Swap with the pane under the pointer',
  shortcutOverlayDoes: 'Land as an overlay, the main view keeps its room',
  shortcutCancelDoes: 'Cancel the drag',
  shortcutDragPastEdge: 'Drag past the edge',
  shortcutPopOutDoes: 'Pop out into its own window',
  shortcutDragGap: 'Drag the gap',
  shortcutResizeDoes: 'Resize neighbours; double-click evens them',
  mainLabel: 'Main view',
  gripLabel: 'Main',
  moveMainHint: (mainLabel: string) => `Drag to move the ${mainLabel.toLowerCase()}`,
  dragSwapLabel: (label: string) => `${label} · swap`,
  dragOverlayLabel: (label: string) => `${label} · overlay`,
  hintSwap: 'Swap',
  hintPopOut: 'Release to pop out',
  hintStays: 'This widget stays in the app',
  ghostSwap: 'swap',
  ghostOverlay: 'overlay',
  ghostCancel: 'cancel',
  ghostPastEdge: 'Past the edge',
  ghostPopOut: 'pop out',
  ghostStays: 'stays in the app',
};

export { WIDGET_STRINGS };
