/* @layer renderer-components @kind data */
const WIDGET_STRINGS = {
  titlebarHint: 'Drag to move. Hold Alt to peek at the main view. While dragging: Shift swaps, Ctrl overlays, Esc cancels, past the window edge pops out.',
  outHint: 'Drag to move the window. Drop it over the app to put it back. Near an edge of the app or another widget, it snaps.',
  pinTitleOff: 'Pin: off. Click for always on top.',
  pinTitleTop: 'Pin: always on top. Click to follow the app.',
  pinTitleWithApp: 'Pin: with the app. Click to unpin.',
  optionsFor: (title: string) => `${title} options`,
  shortcutsSection: 'Shortcuts',
  showShortcuts: 'Show shortcuts',
  hideShortcuts: 'Hide shortcuts',
  shortcutsHint: 'The keys and drags the dock answers to, in a list beside this panel',
  resetWidget: 'Reset this widget',
  resetHint: 'Forgets its place and look and goes back to the defaults',
  closeHint: 'Closes this panel. Esc or a click outside closes it too',
  placement: 'Placement',
  dockLeft: 'Dock left',
  dockLeftHint: 'Takes the left edge of the app',
  dockRight: 'Dock right',
  dockRightHint: 'Takes the right edge of the app',
  dockTop: 'Dock top',
  dockTopHint: 'Takes the top edge of the app',
  dockBottom: 'Dock bottom',
  dockBottomHint: 'Takes the bottom edge of the app',
  float: 'Float',
  floatHint: 'Hovers over the main view, free to move',
  ownWindow: 'Own window',
  ownWindowHint: 'Leaves the app for a window of its own',
  popInHint: 'Back into the app, where it was docked before',
  mainView: 'Main view',
  makeRoom: 'Make room',
  makeRoomHint: 'The main view shrinks to fit this widget',
  overlay: 'Overlay',
  overlayHint: 'Lies over the main view, which keeps its size',
  opacity: 'Opacity',
  opacityValue: (percent: number) => `Opacity ${percent}%`,
  opacityHint: 'How solid the frame is. Pointing at the widget makes it solid',
  show: 'Show',
  showAlways: 'Always',
  showAlwaysHint: 'Stays open all the time',
  contextLabel: 'In context',
  contextHint: 'Shows only while its context is active',
  pin: 'Pin',
  pinOff: 'Off',
  pinOffHint: 'Behaves like any window',
  pinOnTop: 'On top',
  pinOnTopHint: 'Always over every other window',
  pinWithApp: 'With app',
  pinWithAppHint: 'On top exactly when the app is, and comes forward with it',
  snap: 'Snap',
  snapOff: 'Free',
  snapOffHint: 'Moves anywhere, nothing pulls it in',
  snapOn: 'Snap to edges',
  snapOnHint: "Pulls to the edges of the app's and other widgets' windows",
  shortcutDragTitle: 'Drag title',
  shortcutDragTitleDoes: 'Move to a dock edge, a pane, a tab or over the main view',
  shortcutPeekDoes: 'Peek: widgets fold away while held',
  shortcutPlusDrop: '+ drop',
  shortcutSwapDoes: 'Swap with the pane under the pointer',
  shortcutOverlayDoes: 'Land as an overlay, the main view keeps its room',
  shortcutCancelDoes: 'Cancel the drag',
  shortcutDragPastEdge: 'Drag past the edge',
  shortcutPopOutDoes: 'Pop out into its own window',
  shortcutDragGap: 'Drag the gap',
  shortcutResizeDoes: 'Resize neighbours; double-click evens them',
  mainLabel: 'Main view',
  gripLabel: 'Main',
  moveMainHint: (mainLabel: string) => `Drag to move the ${mainLabel.toLowerCase()}`,
  dragSwapLabel: (label: string) => `${label} · swap`,
  dragOverlayLabel: (label: string) => `${label} · overlay`,
  hintSwap: 'Swap',
  hintPopOut: 'Release to pop out',
  hintStays: 'This widget stays in the app',
  ghostSwap: 'swap',
  ghostOverlay: 'overlay',
  ghostCancel: 'cancel',
  ghostPastEdge: 'Past the edge',
  ghostPopOut: 'pop out',
  ghostStays: 'stays in the app',
};

export { WIDGET_STRINGS };
