/* @layer renderer-components @kind data */
const WIDGET_STRINGS = {
  titlebarHint: 'Drag to move. Hold Alt to peek at the main view. While dragging: Shift swaps, Ctrl overlays, Esc cancels, past the window edge pops out.',
  outHint: 'Drag to move the window. Drop it over the app to put it back. Near an edge of the app or another widget, it snaps.',
  pinTitle: (choice: string) => `Pin: ${choice}. Click to choose`,
  optionsFor: (title: string) => `${title} options`,
  shortcutsSection: 'Shortcuts',
  resetWidget: 'Reset this widget',
  resetHint: 'Forgets its place and look and goes back to the defaults',
  placement: 'Placement',
  dockLeft: 'Dock left',
  dockLeftHint: 'Takes the left edge of the app',
  dockRight: 'Dock right',
  dockRightHint: 'Takes the right edge of the app',
  dockTop: 'Dock top',
  dockTopHint: 'Takes the top edge of the app',
  dockBottom: 'Dock bottom',
  dockBottomHint: 'Takes the bottom edge of the app',
  float: 'Float',
  floatHint: 'Hovers over the main view, free to move',
  ownWindow: 'Own window',
  ownWindowHint: 'Leaves the app for a window of its own',
  popInHint: 'Back into the app, where it was docked before',
  mainView: 'Main view',
  makeRoom: 'Make room',
  makeRoomHint: 'The main view shrinks to fit this widget',
  overlay: 'Overlay',
  overlayHint: 'Lies over the main view, which keeps its size',
  opacity: 'Opacity',
  opacityValue: (percent: number) => `${percent}%`,
  show: 'Show',
  showAlways: 'Always',
  showAlwaysHint: 'Stays open all the time',
  contextLabel: 'In context',
  contextHint: 'Shows only while its context is active',
  pin: 'Pin',
  pinOff: 'Off',
  pinOffHint: 'Behaves like any window',
  pinOnTop: 'On top',
  pinOnTopHint: 'Always over every other window',
  snapOffHint: 'Moves anywhere, nothing pulls it in',
  snapOn: 'Snap to edges',
  snapOnHint: "Pulls to the edges of the app's and other widgets' windows",
  sync: 'Sync with main window',
  syncOnHint: 'Follows the main window and shares its taskbar entry',
  syncOffHint: 'Ignores the main window and has a taskbar entry of its own',
  guideMoving: 'Moving window',
  guideResizing: 'Resizing window',
  guideSnapping: 'Snaps to corners and edges',
  guideSnappingOff: 'Snapping off',
  guideMoveFree: 'Move without snapping',
  guideResizeFree: 'Resize without snapping',
  guideResizeAlone: 'On a shared edge: resize this window only',
  guideAnnounce: (mode: string, snapping: boolean) => (snapping ? mode : `${mode}, snapping off`),
  shortcutDragTitle: 'Drag title',
  shortcutDragTitleDoes: 'Move to a dock edge, a pane, a tab or over the main view',
  shortcutPeekDoes: 'Peek: widgets fold away while held',
  shortcutPlusDrop: '+ drop',
  shortcutSwapDoes: 'Swap with the pane under the pointer',
  shortcutOverlayDoes: 'Land as an overlay, the main view keeps its room',
  shortcutCancelDoes: 'Cancel the drag',
  shortcutDragPastEdge: 'Drag past the edge',
  shortcutPopOutDoes: 'Pop out into its own window',
  shortcutDragGap: 'Drag the gap',
  shortcutResizeDoes: 'Resize neighbours; double-click evens them',
  mainLabel: 'Main view',
  gripLabel: 'Main',
  moveMainHint: (mainLabel: string) => `Drag to move the ${mainLabel.toLowerCase()}`,
  dragSwapLabel: (label: string) => `${label} · swap`,
  dragOverlayLabel: (label: string) => `${label} · overlay`,
  hintSwap: 'Swap',
  hintPopOut: 'Release to pop out',
  hintStays: 'This widget stays in the app',
  ghostSwap: 'swap',
  ghostOverlay: 'overlay',
  ghostCancel: 'cancel',
};

export { WIDGET_STRINGS };
