/* @layer renderer-components @kind data */
const DEFAULT_RATIO = 0.58;
const DEFAULT_SNAP = 0.14;
const DEFAULT_MIN_RATIO = 0.2;
const DEFAULT_MAX_RATIO = 0.8;
const KEY_STEP = 2;
const KEY_STEP_LARGE = 10;

export { DEFAULT_MAX_RATIO, DEFAULT_MIN_RATIO, DEFAULT_RATIO, DEFAULT_SNAP, KEY_STEP, KEY_STEP_LARGE };
